name = "ai-conversation-edge"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "ai-conversation-edge-prod"

[env.staging]
name = "ai-conversation-edge-staging"

[[kv_namespaces]]
binding = "AI_CONFIG"
id = "db5024c642b44690a9c552c098918da5"
preview_id = "db5024c642b44690a9c552c098918da5"

[build]
command = "npm run build"
